version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: erp-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    environment:
      - DATABASE_URL=mysql://erp_user:strong_password@db:3306/erp_db
      - NODE_ENV=production
    depends_on:
      - db

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: erp-admin
    ports:
      - "80:80"
    volumes:
      - ./admin:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: erp-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: erp_db
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: strong_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: erp-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  db_data:
